version: '3.1'

services:

  myflask:
    image: myflask:v1.0.0
    build: ./src
    ports:
      - 8080:8080
    environment:
      MONGODB_HOST: mongo

  mongo:
    image: mongo:8.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:1-20-alpine3.19
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: example
      ME_CONFIG_BASICAUTH_PASSWORD: example
